/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PerformanceMetricService } from "../performanceMetric.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PerformanceMetricCreateInput } from "./PerformanceMetricCreateInput";
import { PerformanceMetric } from "./PerformanceMetric";
import { PerformanceMetricFindManyArgs } from "./PerformanceMetricFindManyArgs";
import { PerformanceMetricWhereUniqueInput } from "./PerformanceMetricWhereUniqueInput";
import { PerformanceMetricUpdateInput } from "./PerformanceMetricUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PerformanceMetricControllerBase {
  constructor(
    protected readonly service: PerformanceMetricService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PerformanceMetric })
  @nestAccessControl.UseRoles({
    resource: "PerformanceMetric",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPerformanceMetric(
    @common.Body() data: PerformanceMetricCreateInput
  ): Promise<PerformanceMetric> {
    return await this.service.createPerformanceMetric({
      data: {
        ...data,

        employee: data.employee
          ? {
              connect: data.employee,
            }
          : undefined,
      },
      select: {
        callsMade: true,
        conversionRate: true,
        createdAt: true,
        emailsSent: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        meetingsBooked: true,
        metricType: true,
        recordedDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PerformanceMetric] })
  @ApiNestedQuery(PerformanceMetricFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PerformanceMetric",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async performanceMetrics(
    @common.Req() request: Request
  ): Promise<PerformanceMetric[]> {
    const args = plainToClass(PerformanceMetricFindManyArgs, request.query);
    return this.service.performanceMetrics({
      ...args,
      select: {
        callsMade: true,
        conversionRate: true,
        createdAt: true,
        emailsSent: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        meetingsBooked: true,
        metricType: true,
        recordedDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PerformanceMetric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PerformanceMetric",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async performanceMetric(
    @common.Param() params: PerformanceMetricWhereUniqueInput
  ): Promise<PerformanceMetric | null> {
    const result = await this.service.performanceMetric({
      where: params,
      select: {
        callsMade: true,
        conversionRate: true,
        createdAt: true,
        emailsSent: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        meetingsBooked: true,
        metricType: true,
        recordedDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PerformanceMetric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PerformanceMetric",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePerformanceMetric(
    @common.Param() params: PerformanceMetricWhereUniqueInput,
    @common.Body() data: PerformanceMetricUpdateInput
  ): Promise<PerformanceMetric | null> {
    try {
      return await this.service.updatePerformanceMetric({
        where: params,
        data: {
          ...data,

          employee: data.employee
            ? {
                connect: data.employee,
              }
            : undefined,
        },
        select: {
          callsMade: true,
          conversionRate: true,
          createdAt: true,
          emailsSent: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,
          meetingsBooked: true,
          metricType: true,
          recordedDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PerformanceMetric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PerformanceMetric",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePerformanceMetric(
    @common.Param() params: PerformanceMetricWhereUniqueInput
  ): Promise<PerformanceMetric | null> {
    try {
      return await this.service.deletePerformanceMetric({
        where: params,
        select: {
          callsMade: true,
          conversionRate: true,
          createdAt: true,
          emailsSent: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,
          meetingsBooked: true,
          metricType: true,
          recordedDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
